### ISSUE TITLE
Feature request: Grouping in Reports

### ISSUE THREAD

**Issue by Scridgeon** [elvishcraftsman/time-tracker#2]
Tasks and Clients were just released as options in the time tracking section of the app. It would be nice to have those as options in the report section to group by. Furtherance has a decent implementation of this that could be a good starting point for ideas.

**Comment by elvishcraftsman** [comment]
I like the idea of how Furtherance does it, but it feels a bit clunky to me. I think I can definitely learn something from it though. I think the hierarchy idea is good, and maybe there could be multiple levels of hierarchy.

I'd like Time Tracker to have a pretty decent reporting system. I'm thinking that one could build multiple preset reports to page through, with the ability to choose filters and what to group by and in what hierarchy. Thoughts?

My own needs for reporting are fairly simple. Would you mind giving an example of what an optimal report would look like for your workflow, for reference?

**Comment by elvishcraftsman** [comment]
@Scridgeon  Okay, so I overhauled the reporting, as stated. It still needs some UX work, but I don't know of any bugs at the moment. If you'd like to test out what I have so far, it would be great to know if it's working well and if it fills your needs or if there are more features you'd need. 

You can download the test version [here](https://github.com/elvishcraftsman/time-tracker/blob/test/com.lynnmichaelmartin.TimeTracker.flatpak) and install it via the command line. Might need to uninstall your current version first; not sure.

I do plan to insert a button in each report for downloading a CSV file of it. If that were added, any thoughts on what info should be included in the CSV file?

I'll keep working on it, and when the UX is better, I'll push out an update through Flathub.

**Comment by Scridgeon** [comment]
I tried installing the flatpak but I'm getting an error: "Invalid checksum of length 0 expected 32"

**Comment by elvishcraftsman** [comment]
Hmm. I've never had a problem installing flatpaks that I generated myself, even though they're not signed. You could try installing it with the flag --no-static-delta. Or I may just need to look into how to sign flatpaks that I generate.

**Comment by elvishcraftsman** [comment]
What OS are you using?

**Comment by Scridgeon** [comment]
I'm on Fedora Silverblue but I've also tried to install the Flatpak on Fedora workstation 39 and Ubuntu 22.04. Same error on all 3 distros. Fedora workstation and Ubuntu were fresh installs.

**Comment by elvishcraftsman** [comment]
Okay, that's really odd. I guess I'll just keep bug-testing what I have and release it here in the next week or so. I'll look forward to hearing how it works for you.

**Comment by elvishcraftsman** [comment]
@Scridgeon I just pushed out an update that has way more flexibility with reporting. Let me know what you think!

**Comment by Scridgeon** [comment]
That's a good update. Editing the preset reports is clunky but it makes sense once you understand how it works.
Thanks for making this update. You can close this issue.

**Comment by elvishcraftsman** [comment]
Awesome. If in future you have suggestions for a better flow, definitely open a feature request.
