### ISSUE TITLE
UX Suggestion: Don't reset project selection and task title between time logs

### ISSUE THREAD

**Issue by largestgithubuseronearth** [elvishcraftsman/time-tracker#4]
Every time you stop a time log, it resets the project dropdown back to no project. This really gets annoying when you take lots of short breaks during the day. This is just a personal observation but I resume a task more often than I switch between tasks throughout the day, and I rarely switch between projects in a day.

I hope you'll consider changing the UI behavior based on my feedback. Thanks.

**Comment by elvishcraftsman** [comment]
Great suggestion. For my own workflow, that wouldn't be a help, but for people who mainly use the same task, that should definitely be an option. I'll add that as a setting in the next release.

**Comment by elvishcraftsman** [comment]
You should see an update before too long that adds that as a setting in preferences. Let me know if it's not working.
